version: '3.8'

services:
  app:
    image: node:14
    container_name: express_app
    working_dir: /app
    volumes:
      - /workspace:/app
    environment:
      - MONGO_URI=mongodb://db:27017/mydb
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
    ports:
      - 3000:3000

  db:
    image: mongo:4.4
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: